import readline from 'readline';
import crypto from 'crypto';
import { usersCol, rolesCol, generateId } from '../lib/mongodb';

function hashPassword(password: string, customSalt?: string): string {
  const salt = customSalt || crypto.randomBytes(16).toString('hex');
  const hash = crypto.pbkdf2Sync(password, salt, 10000, 64, 'sha512').toString('hex');
  return `${salt}:${hash}`;
}

function generateTemporaryPassword(): string {
  const letters = 'ABCDEFGHJKLMNPQRSTUVWXYZ';
  const numbers = '23456789';

  let pass = 'Admin@';
  for (let i = 0; i < 4; i++) {
    pass += numbers.charAt(Math.floor(Math.random() * numbers.length));
  }
  for (let i = 0; i < 2; i++) {
    pass += letters.charAt(Math.floor(Math.random() * letters.length));
  }
  return pass;
}

function parseArgs(): Record<string, string> {
  const args: Record<string, string> = {};
  const argv = process.argv.slice(2);
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg.startsWith('--')) {
      const equalIdx = arg.indexOf('=');
      if (equalIdx !== -1) {
        const key = arg.slice(2, equalIdx);
        const val = arg.slice(equalIdx + 1);
        args[key] = val;
      } else {
        const key = arg.slice(2);
        const next = argv[i + 1];
        if (next && !next.startsWith('--')) {
          args[key] = next;
          i++;
        } else {
          args[key] = 'true';
        }
      }
    }
  }
  return args;
}

async function promptQuestion(rl: readline.Interface, question: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer.trim());
    });
  });
}

async function main() {
  console.log('\n=============================================================');
  console.log('   SECUREYE HRMS SUITE — Super Admin Provisioning Tool (MongoDB)   ');
  console.log('=============================================================\n');

  const flags = parseArgs();
  let name = flags.name || flags.n || '';
  let mobileNumber = flags.mobile || flags.m || flags.phone || '';
  let email = flags.email || flags.e || '';
  let password = flags.password || flags.p || '';

  if ((!name || !mobileNumber || !email) && process.stdin.isTTY) {
    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
    });

    if (!name) {
      name = await promptQuestion(rl, '» Enter Full Name: ');
    }
    if (!mobileNumber) {
      mobileNumber = await promptQuestion(rl, '» Enter Mobile Number (10 digits): ');
    }
    if (!email) {
      email = await promptQuestion(rl, '» Enter Corporate Email: ');
    }
    if (!password) {
      const pAns = await promptQuestion(rl, '» Enter Password (leave blank to auto-generate): ');
      if (pAns) password = pAns;
    }

    rl.close();
  }

  name = name.trim();
  mobileNumber = mobileNumber.replace(/\D/g, '').slice(-10);
  email = email.trim().toLowerCase();

  if (!name) {
    console.error('❌ Error: Name is required.');
    process.exit(1);
  }
  if (!mobileNumber || mobileNumber.length < 10) {
    console.error('❌ Error: Valid 10-digit mobile number is required.');
    process.exit(1);
  }
  if (!email || !email.includes('@')) {
    console.error('❌ Error: Valid email address is required.');
    process.exit(1);
  }

  const isAutoGenerated = !password;
  if (!password) {
    password = generateTemporaryPassword();
  }

  const roles = await rolesCol();
  const users = await usersCol();

  // 1. Ensure SUPER_ADMIN role exists
  let superAdminRole = await roles.findOne({ name: 'SUPER_ADMIN' });
  if (!superAdminRole) {
    const roleId = 'role_super_admin';
    await roles.insertOne({
      id: roleId,
      name: 'SUPER_ADMIN',
      description: 'Wildcard Administrator with full system control',
      isSystem: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
    superAdminRole = { id: roleId, name: 'SUPER_ADMIN' };
  }

  const passwordHash = hashPassword(password);
  const existingUser = await users.findOne({ mobileNumber });

  let action = 'CREATED';
  let userId = '';

  const now = new Date();

  if (existingUser) {
    userId = existingUser.id || existingUser._id.toString();
    await users.updateOne(
      { _id: existingUser._id },
      {
        $set: {
          name,
          email,
          passwordHash,
          roleId: superAdminRole.id,
          status: 'ACTIVE',
          mustChangePassword: isAutoGenerated,
          updatedAt: now,
        },
      }
    );
    action = 'ELEVATED';
  } else {
    userId = generateId();
    await users.insertOne({
      id: userId,
      mobileNumber,
      passwordHash,
      name,
      email,
      mustChangePassword: isAutoGenerated,
      status: 'ACTIVE',
      roleId: superAdminRole.id,
      createdAt: now,
      updatedAt: now,
    });
    action = 'CREATED';
  }

  console.log('\n-------------------------------------------------------------');
  console.log(`✅ SUPER ADMIN SUCCESSFULLY ${action} ON MONGODB ATLAS!`);
  console.log('-------------------------------------------------------------');
  console.log(`  User ID:       ${userId}`);
  console.log(`  Full Name:     ${name}`);
  console.log(`  Mobile Number: ${mobileNumber}`);
  console.log(`  Email Address: ${email}`);
  console.log(`  Role Assigned: SUPER_ADMIN (Wildcard Privileges)`);
  console.log(`  Password:      ${password}`);
  if (isAutoGenerated) {
    console.log(`  Note:          Temporary password generated. User will be asked to update on login.`);
  }
  console.log('-------------------------------------------------------------');
  console.log('You can now log in immediately at http://localhost:3000/login\n');

  process.exit(0);
}

main().catch((err) => {
  console.error('Fatal Error creating Super Admin:', err);
  process.exit(1);
});
