#!/usr/bin/env node
const readline = require('readline');
const { DatabaseSync } = require('node:sqlite');
const path = require('path');
const crypto = require('crypto');

// Suppress experimental sqlite warning
process.removeAllListeners('warning');

const DB_PATH = path.join(process.cwd(), 'prisma', 'dev.db');

function hashPassword(password, customSalt) {
  const salt = customSalt || crypto.randomBytes(16).toString('hex');
  const hash = crypto.pbkdf2Sync(password, salt, 10000, 64, 'sha512').toString('hex');
  return `${salt}:${hash}`;
}

function generateTemporaryPassword() {
  const letters = 'ABCDEFGHJKLMNPQRSTUVWXYZ';
  const numbers = '23456789';

  let pass = 'Admin@';
  for (let i = 0; i < 4; i++) {
    pass += numbers.charAt(Math.floor(Math.random() * numbers.length));
  }
  for (let i = 0; i < 2; i++) {
    pass += letters.charAt(Math.floor(Math.random() * letters.length));
  }
  return pass;
}

function parseArgs() {
  const args = {};
  const argv = process.argv.slice(2);
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg.startsWith('--')) {
      const equalIdx = arg.indexOf('=');
      if (equalIdx !== -1) {
        const key = arg.slice(2, equalIdx);
        const val = arg.slice(equalIdx + 1);
        args[key] = val;
      } else {
        const key = arg.slice(2);
        const next = argv[i + 1];
        if (next && !next.startsWith('--')) {
          args[key] = next;
          i++;
        } else {
          args[key] = 'true';
        }
      }
    }
  }
  return args;
}

function promptQuestion(rl, question) {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer.trim());
    });
  });
}

async function main() {
  console.log('\n=============================================================');
  console.log('   KERNN HRMS SUITE — Super Admin Provisioning Tool (CLI)   ');
  console.log('=============================================================\n');

  const flags = parseArgs();
  let name = flags.name || flags.n || '';
  let mobileNumber = flags.mobile || flags.m || flags.phone || '';
  let email = flags.email || flags.e || '';
  let password = flags.password || flags.p || '';

  if ((!name || !mobileNumber || !email) && process.stdin.isTTY) {
    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
    });

    if (!name) {
      name = await promptQuestion(rl, '» Enter Full Name: ');
    }
    if (!mobileNumber) {
      mobileNumber = await promptQuestion(rl, '» Enter Mobile Number (10 digits): ');
    }
    if (!email) {
      email = await promptQuestion(rl, '» Enter Corporate Email: ');
    }
    if (!password) {
      const pAns = await promptQuestion(rl, '» Enter Password (leave blank to auto-generate): ');
      if (pAns) password = pAns;
    }

    rl.close();
  }

  name = (name || '').trim();
  mobileNumber = (mobileNumber || '').replace(/\D/g, '').slice(-10);
  email = (email || '').trim().toLowerCase();

  if (!name) {
    console.error('❌ Error: Full name is required.');
    console.log('Usage: npm run admin:create -- --name="John Doe" --mobile="9876543210" --email="john@kernn.com"\n');
    process.exit(1);
  }
  if (!mobileNumber || mobileNumber.length < 10) {
    console.error('❌ Error: Valid 10-digit mobile number is required.');
    process.exit(1);
  }
  if (!email || !email.includes('@')) {
    console.error('❌ Error: Valid corporate email address is required.');
    process.exit(1);
  }

  const isAutoGenerated = !password;
  if (!password) {
    password = generateTemporaryPassword();
  }

  const db = new DatabaseSync(DB_PATH);

  let superAdminRole = db.prepare(`SELECT id FROM Role WHERE name = 'SUPER_ADMIN'`).get();
  if (!superAdminRole) {
    const roleId = 'role_' + Math.random().toString(36).substring(2, 10);
    db.prepare(`
      INSERT INTO Role (id, name, description, isSystem, createdAt, updatedAt)
      VALUES (?, 'SUPER_ADMIN', 'Wildcard Administrator with full system control', 1, datetime('now'), datetime('now'))
    `).run(roleId);
    superAdminRole = { id: roleId };
  }

  const passwordHash = hashPassword(password);
  const existingUser = db.prepare(`SELECT id, name, roleId FROM User WHERE mobileNumber = ?`).get(mobileNumber);

  let action = 'CREATED';
  let userId = '';

  if (existingUser) {
    userId = existingUser.id;
    db.prepare(`
      UPDATE User 
      SET name = ?, email = ?, passwordHash = ?, roleId = ?, status = 'ACTIVE', mustChangePassword = ?, updatedAt = datetime('now')
      WHERE id = ?
    `).run(name, email, passwordHash, superAdminRole.id, isAutoGenerated ? 1 : 0, userId);
    action = 'ELEVATED TO SUPER ADMIN';
  } else {
    userId = 'usr_' + Math.random().toString(36).substring(2, 12);
    db.prepare(`
      INSERT INTO User (id, mobileNumber, passwordHash, name, email, mustChangePassword, status, roleId, createdAt, updatedAt)
      VALUES (?, ?, ?, ?, ?, ?, 'ACTIVE', ?, datetime('now'), datetime('now'))
    `).run(userId, mobileNumber, passwordHash, name, email, isAutoGenerated ? 1 : 0, superAdminRole.id);
    action = 'CREATED';
  }

  console.log('\n-------------------------------------------------------------');
  console.log(`✅ SUPER ADMIN SUCCESSFULLY ${action}!`);
  console.log('-------------------------------------------------------------');
  console.log(`  User ID:       ${userId}`);
  console.log(`  Full Name:     ${name}`);
  console.log(`  Mobile Number: ${mobileNumber}`);
  console.log(`  Email Address: ${email}`);
  console.log(`  Role Assigned: SUPER_ADMIN (Full Wildcard Access)`);
  console.log(`  Password:      ${password}`);
  if (isAutoGenerated) {
    console.log(`  Note:          Temporary password generated. User will be asked to update on login.`);
  }
  console.log('-------------------------------------------------------------');
  console.log('You can now log in immediately at http://localhost:3000/login\n');

  process.exit(0);
}

main().catch((err) => {
  console.error('Fatal Error creating Super Admin:', err);
  process.exit(1);
});
